version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: rentee
      POSTGRES_USER: rentee_user
      POSTGRES_PASSWORD: suPersecr@#t678*&^
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: ghcr.io/rentee-org/rentee-backend:latest
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    image: ghcr.io/rentee-org/rentee-frontend:latest
    restart: always
    ports:
      - "80:80"

volumes:
  pgdata:
